### ISSUE TITLE
Support for RabbitMQ vhosts?

### ISSUE THREAD

**Issue by elasticdotventures** [babinc/amqp-client-cli#1]
is there an obvious way to specify which RabbitMQ Vhost ?

**Comment by elasticdotventures** [comment]
https://www.rabbitmq.com/uri-spec.html

**Comment by elasticdotventures** [comment]
amqp_URI       = "amqp://" amqp_authority [ "/" vhost ] [ "?" query ]

**Comment by babinc** [comment]
Unfortunately I did not add the feature of vhost in the connection. But it is something I can work on if you think this is a feature that is needed.

**Comment by keltia** [comment]
Yes, it is needed.  Just tumbled on this very issue, the amqp broker I'm supposed to connect to also has vhosts.

**Comment by babinc** [comment]
@keltia I am going to work on adding this today. Do you have an environment you can test vhost on for me? And would you mind testing?

**Comment by keltia** [comment]
Ooops I did it :)
https://github.com/babinc/amqp-client-cli/pull/4

**Comment by keltia** [comment]
And yes, I can test it.  Mine works for me right now, I can connect.

**Comment by babinc** [comment]
Very nice! Thanks. I'll merge it  👍
